apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: default
spec:
  serviceAccountName: test-app-sa
  containers:
    - name: test-app
      image: fedora:latest
      command: ['sleep', 'infinity']
      ports:
        - containerPort: 8080
      envFrom:
      - configMapRef:
          name: conjur-configmap
      volumeMounts:
      - mountPath: /run/conjur
        name: conjur-access-token
        readOnly: true
  initContainers:
  - image: cyberark/conjur-authn-k8s-client
    imagePullPolicy: Always
    name: authenticator
    env:
      - name: CONJUR_AUTHN_LOGIN
        value: host/test-app
      - name: CONTAINER_MODE
        value: init
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: CONJUR_ACCOUNT
        value: devorg
      - name: CONJUR_AUTHN_LOGIN
        value: test-app
      - name: CONJUR_AUTHN_TOKEN_FILE
        value: /run/conjur/access-token
      - name: CONJUR_SSL_CERTIFICATE
        valueFrom:
          configMapKeyRef:
            name: default
            key: ssl-certificate
    volumeMounts:
      - mountPath: /run/conjur
        name: conjur-access-token
      - mountPath: /etc/conjur/ssl
        name: conjur-client-ssl
  volumes:
    - name: conjur-access-token
      emptyDir:
        medium: Memory
    - name: conjur-client-ssl
      emptyDir:
        medium: Memory
