apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: fedora
      image: fedora:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: secret
          mountPath: "/etc/secret"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: db-credentials
