---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-provider-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-provider-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: [ "get", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: secrets-provider-role-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: secrets-provider-service-account
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-provider-role
