apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-provider
  namespace: default
spec:
  template:
    metadata:
    spec:
      serviceAccountName: secrets-provider-service-account
      containers:
      - image: docker.io/cyberark/secrets-provider-for-k8s:1.4.0
        imagePullPolicy: IfNotPresent
        name: cyberark-secrets-provider-for-k8s
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name

        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace

        - name: CONJUR_AUTHN_LOGIN
          value: "host/secrets-provider-app"

        - name: SECRETS_DESTINATION
          value: k8s_secrets

        # Enables the support of multiple Kubernetes applications
        - name: CONTAINER_MODE
          value: application

        - name: K8S_SECRETS
          value: db-credentials
        envFrom:
        - configMapRef:
            name: conjur-configmap
      restartPolicy: Never
  backoffLimit: 0
